print("Hi and welcome to EchoBot.")
username = input("What is your name?")
print("Hi "+username+". This chatbot will repeat what you will say.")
stuff_to_echo = input("Please enter something to repeat")
print("You said: "+stuff_to_echo)
print("Bye bye.")
